export * from './tabs.module';
export * from './tab';
export * from './tab-group';
export * from './tab-header';
export * from './tab-body';
export * from './tab-label';
export * from './tab-nav-bar';
export * from './tab-content';
export * from './tab-label-wrapper';
