import chalk from 'chalk';
import { Dgeni } from 'dgeni';
import { defer, of } from 'rxjs';
import { catchError, concatAll, filter, map, toArray } from 'rxjs/operators';

import { apiDocsPackage } from './docs-dgeni-package/package';

/**
 * Maps every input that accepts a fixed set of string values to those values, so that the search can
 * find inputs by a value such as `primary`. Inputs without such a set are left out to keep the
 * search payload small.
 */
const getInputValueMap = (doc) =>
  doc.properties
    .filter((p) => p.isDirectiveInput && p.inputValues.length > 0)
    .map((p) => ({ name: bindingName(p), values: p.inputValues }));

/** The name an input or output is bound by in a template. */
const bindingName = (property) => property.nameAlias || property.name;

/** Search entry of a directive or component. */
const getDirectiveEntry = (doc) => ({
  name: doc.name,
  directiveExportAs: doc.directiveExportAs,
  directiveSelectors: doc.directiveSelectors,
  inputs: doc.properties.filter((p) => p.isDirectiveInput).map(bindingName),
  outputs: doc.properties.filter((p) => p.isDirectiveOutput).map(bindingName),
  inputValues: getInputValueMap(doc),
  title: doc.description,
});

export const build = ({ source, dest }) => {
  apiDocsPackage.config((readFilesProcessor, readTypeScriptModules, writeFilesProcessor) => {
    readFilesProcessor.basePath = source;
    readTypeScriptModules.basePath = source;
    writeFilesProcessor.outputFolder = dest;
  });
  // defer will not execute the async function until subscribed.
  // that ensures that DGeni is not run before up in the queue
  // (see main.ts where we use concatAllto queue our tasks)
  return defer(async () => {
    // Create new instance in here to prevent a memory leak
    const dgeni = new Dgeni([apiDocsPackage]);
    console.log(chalk.green('Generating API docs'));
    return dgeni.generate();
  }).pipe(
    // travers received documents to populate a list of generated api files
    // so we can determine if a module has an api table available

    // process each document separately with rxj
    concatAll(),

    // we are only interested in the docs generated by the grouping dgeni processor
    filter((value: any) => value.docType === 'componentGroup'),
    // from that document grab only one key
    map((value) => ({
      id: value.packageName,
      ngModule: value.ngModule?.name,
      // Lets the viewer hide the slots tab for entry points that have no slots at all.
      hasSlots: value.contentSlotClasses.length > 0,
      directive: value.directives.map(getDirectiveEntry),
      component: value.components.map(getDirectiveEntry),
      services: value.services.map((t) => ({
        name: t.name,
        title: t.description,
      })),
      classes: value.additionalClasses.map((t) => ({
        name: t.name,
        title: t.description,
      })),
      interface: value.additionalInterfaces.map((t) => ({
        name: t.name,
        title: t.description,
      })),
      typeAlias: value.additionalTypeAliases.map((t) => ({
        name: t.name,
        title: t.description,
      })),
    })),
    toArray(),
    map((packages) => ({ api: packages })),
    catchError((error) => {
      console.error(chalk.magentaBright('Error while processing API docs'));
      console.error(chalk.magentaBright(error));
      return of(null);
    }),
  );
};
