import { readFileSync, readdirSync } from 'fs';
import { resolve } from 'path';

import { writeContentsToFile } from './utils';

/**
 * Settings
 */
const settings = {
  componentsPath: '../generated/components',
  tagsPath: '../static/tags.json',
  outputPath: '../generated/skill.md',
  version: JSON.parse(readFileSync(resolve(__dirname, '../../src/package.json'), 'utf-8')).version,
};

/**
 * Regex to extract frontmatter YAML between --- markers
 */
const frontmatterRegex = /^---\s*\n([\s\S]*?)\n---/;

/**
 * Extracts key fields from component frontmatter.
 */
function parseComponentFrontmatter(content: string): {
  title: string;
  category: string;
  selector: string;
} | null {
  const match = content.match(frontmatterRegex);
  if (!match) {
    return null;
  }
  const yaml = match[1];

  const titleMatch = yaml.match(/^title:\s*(.+)$/m);
  const categoryMatch = yaml.match(/^category:\s*(.+)$/m);
  const selectorMatch = yaml.match(/^\s+selector:\s*(.+)$/m);

  if (!titleMatch) {
    return null;
  }

  return {
    title: titleMatch[1].trim(),
    category: categoryMatch ? categoryMatch[1].trim() : '',
    selector: selectorMatch ? selectorMatch[1].trim() : '',
  };
}

/**
 * Builds the component catalog table from generated component files.
 */
function buildCatalogTable(): string {
  const componentsDir = resolve(__dirname, settings.componentsPath);
  const files = readdirSync(componentsDir).filter((f) => f.endsWith('.md'));

  const rows: string[] = [];
  for (const file of files) {
    const content = readFileSync(resolve(componentsDir, file), 'utf-8');
    const meta = parseComponentFrontmatter(content);
    if (meta && meta.category === 'components') {
      const name = file.replace('.md', '');
      rows.push(`| ${name} | \`${meta.selector || '—'}\` | ${meta.title} |`);
    }
  }

  return ['| Component | Main Selector | Title |', '|-----------|---------------|-------|', ...rows].join('\n');
}

/**
 * Builds the "Find by Use Case" section from tags.json.
 */
function buildTagSection(): string {
  const tags: Record<string, string[]> = JSON.parse(
    readFileSync(resolve(__dirname, settings.tagsPath), 'utf-8'),
  );

  // Pick the most useful top-level categories
  const selectedTags = [
    'form',
    'navigation',
    'table',
    'feedback',
    'layout',
    'overlay',
    'media',
    'interaction',
    'selection',
    'typography',
  ];

  const lines: string[] = [];
  for (const tag of selectedTags) {
    if (tags[tag]) {
      lines.push(`- **${tag}**: ${tags[tag].join(', ')}`);
    }
  }
  return lines.join('\n');
}

/**
 * Assembles the full skill markdown.
 */
function buildSkill(): string {
  const catalog = buildCatalogTable();
  const tagSection = buildTagSection();

  return `<!-- Generated by @allianz/ng-aquila v${settings.version} — do not edit manually -->
# Aquila – Angular Brand Kit Component Library

Aquila (open source) / Angular Brand Kit (formerly NDBX) is the Allianz Design System
component library for Angular.

## Modern Angular
Aquila requires modern Angular (v19+). Always use the latest Angular patterns:
standalone components, signals, new control flow (\`@if\`, \`@for\`), \`inject()\`, etc.
For Angular-specific coding conventions, refer to the official Angular Skill from the Angular team.

## Import Rules
To import any Aquila component, construct the path as follows:
1. Domain: \`@allianz\`
2. Library: \`/ng-aquila\`
3. Component: \`/{component-name}\`

Example: \`import { NxButtonModule } from '@allianz/ng-aquila/button';\`

## Installation
\`\`\`bash
ng add @allianz/ng-aquila
\`\`\`
Requires \`@angular/cdk\` as a peer dependency (installed automatically by \`ng add\`).

## Aquila-Specific Rules
- Never use \`NxInput\` directive without wrapping it in \`nx-formfield\`
- Always import \`NxInputModule\` when using \`NxInputDirective\`
- Use \`nx-error\` with \`nxFormfieldError\` for validation messages inside formfields
- Always set \`type="button"\` on \`<button nxButton>\` to prevent accidental form submission
- Prefer Reactive Forms over Template-driven forms with Aquila form components
- Import individual component modules to optimize bundle size
- Do not use inline CSS styles; rely on Aquila's built-in styling and utility classes

## Accessibility
Aquila components have built-in accessibility support. When using them:
- Always provide labels for form fields (use the \`label\` input on \`nx-formfield\`)
- Use \`aria-label\` or \`aria-labelledby\` where a visible label is not present
- Ensure meaningful text for buttons and links (avoid "click here")
- Use \`nx-message\` for user-facing status messages (they announce via ARIA live regions)

## Grid System
Aquila uses a 12-column responsive grid with \`nxLayout\`, \`nxRow\`, and \`nxCol\`.
The \`nxCol\` attribute accepts comma-separated values for responsive breakpoints
in order: tiny, small, medium, large, xlarge, 2xlarge, 3xlarge.
If fewer values are provided, the last one repeats for remaining breakpoints.

### Two-column layout (full width on mobile, half on desktop)
\`\`\`html
<div nxLayout="grid">
  <div nxRow>
    <div nxCol="12,12,6">Left content</div>
    <div nxCol="12,12,6">Right content</div>
  </div>
</div>
\`\`\`

### Three-column form layout
\`\`\`html
<div nxLayout="grid">
  <div nxRow>
    <div nxCol="12,4">
      <nx-formfield label="First name">
        <input nxInput type="text" />
      </nx-formfield>
    </div>
    <div nxCol="12,4">
      <nx-formfield label="Last name">
        <input nxInput type="text" />
      </nx-formfield>
    </div>
    <div nxCol="12,4">
      <nx-formfield label="Email">
        <input nxInput type="email" />
      </nx-formfield>
    </div>
  </div>
</div>
\`\`\`

## Component Catalog
${catalog}

## Find Components by Use Case
${tagSection}

## Detailed API
For full component API (inputs, outputs, methods) and code examples,
use the \`search-ndbx-components\` MCP tool, or read the component doc at:
\`node_modules/@allianz/ng-aquila/mcp/generated/components/{component-name}.md\`
`;
}

/**
 * Main
 */
function main() {
  console.log('🧪 Generating skill ...');
  const skill = buildSkill();
  const outPath = resolve(__dirname, settings.outputPath);
  writeContentsToFile({ path: outPath, content: skill });
  console.log(`✅ Skill written to ${outPath}`);
}

try {
  main();
} catch (error) {
  console.error('❌ Error generating skill:', error);
}
