import { readFileSync, readdirSync } from 'fs';
import { resolve } from 'path';

import { writeContentsToFile } from './utils';

/**
 * Settings
 */
const settings = {
  componentsPath: '../generated/components',
  tagsPath: '../static/tags.json',
  templatePath: '../static/skill-template.md',
  outputPath: '../generated/skill.md',
  version: JSON.parse(readFileSync(resolve(__dirname, '../../src/package.json'), 'utf-8')).version,
};

/**
 * Regex to extract frontmatter YAML between --- markers
 */
const frontmatterRegex = /^---\s*\n([\s\S]*?)\n---/;

/**
 * Extracts key fields from component frontmatter.
 */
function parseComponentFrontmatter(content: string): {
  title: string;
  category: string;
  selector: string;
} | null {
  const match = content.match(frontmatterRegex);
  if (!match) {
    return null;
  }
  const yaml = match[1];

  const titleMatch = yaml.match(/^title:\s*(.+)$/m);
  const categoryMatch = yaml.match(/^category:\s*(.+)$/m);
  const selectorMatch = yaml.match(/^\s+selector:\s*(.+)$/m);

  if (!titleMatch) {
    return null;
  }

  return {
    title: titleMatch[1].trim(),
    category: categoryMatch ? categoryMatch[1].trim() : '',
    selector: selectorMatch ? selectorMatch[1].trim() : '',
  };
}

/**
 * Builds the component catalog table from generated component files.
 */
function buildCatalogTable(): string {
  const componentsDir = resolve(__dirname, settings.componentsPath);
  const files = readdirSync(componentsDir).filter((f) => f.endsWith('.md'));

  const rows: string[] = [];
  for (const file of files.sort()) {
    const content = readFileSync(resolve(componentsDir, file), 'utf-8');
    const meta = parseComponentFrontmatter(content);
    if (meta && meta.category === 'components' && meta.selector) {
      const name = file.replace('.md', '');
      rows.push(`| ${name} | \`${meta.selector}\` | ${meta.title} |`);
    }
  }

  return [
    '| Component | Main Selector | Title |',
    '|-----------|---------------|-------|',
    ...rows,
  ].join('\n');
}

/**
 * Builds the "Find by Use Case" section from tags.json.
 */
function buildTagSection(): string {
  const tags: Record<string, string[]> = JSON.parse(
    readFileSync(resolve(__dirname, settings.tagsPath), 'utf-8'),
  );

  // Pick the most useful top-level categories
  const selectedTags = [
    'form',
    'navigation',
    'table',
    'feedback',
    'layout',
    'overlay',
    'media',
    'interaction',
    'selection',
    'typography',
  ];

  const lines: string[] = [];
  for (const tag of selectedTags) {
    if (tags[tag]) {
      lines.push(`- **${tag}**: ${tags[tag].join(', ')}`);
    }
  }
  return lines.join('\n');
}

/**
 * Assembles the full skill markdown from the template.
 */
function buildSkill(): string {
  const catalog = buildCatalogTable();
  const tagSection = buildTagSection();
  const template = readFileSync(resolve(__dirname, settings.templatePath), 'utf-8');

  return `<!-- Generated by @allianz/ng-aquila v${settings.version} -->\n` +
    template
      .replace('{{CATALOG}}', catalog)
      .replace('{{TAGS}}', tagSection);
}

/**
 * Main
 */
function main() {
  console.log('🧪 Generating skill ...');
  const skill = buildSkill();
  const outPath = resolve(__dirname, settings.outputPath);
  writeContentsToFile({ path: outPath, content: skill });
  console.log(`✅ Skill written to ${outPath}`);
}

try {
  main();
} catch (error) {
  console.error('❌ Error generating skill:', error);
}
