import { readFileSync, readdirSync } from 'fs';
import { resolve } from 'path';

import { writeContentsToFile } from './utils';

const base = (rel: string) => resolve(__dirname, rel);
const version = JSON.parse(readFileSync(base('../../src/package.json'), 'utf-8')).version;

function buildCatalogTable(): string {
  const dir = base('../generated/components');
  const rows = readdirSync(dir)
    .filter(f => f.endsWith('.md'))
    .sort()
    .map(file => {
      const content = readFileSync(resolve(dir, file), 'utf-8');
      const fm = content.match(/^---\s*\n([\s\S]*?)\n---/)?.[1] ?? '';
      const title = fm.match(/^title:\s*(.+)$/m)?.[1]?.trim();
      const category = fm.match(/^category:\s*(.+)$/m)?.[1]?.trim();
      const selector = fm.match(/^\s+selector:\s*(.+)$/m)?.[1]?.trim();
      if (category === 'components' && selector) {
        return `| ${file.replace('.md', '')} | \`${selector}\` | ${title} |`;
      }
      return null;
    })
    .filter(Boolean);

  return ['| Component | Main Selector | Title |', '|-----------|---------------|-------|', ...rows].join('\n');
}

function buildTagSection(): string {
  const tags: Record<string, string[]> = JSON.parse(readFileSync(base('../static/tags.json'), 'utf-8'));
  const selected = ['form', 'navigation', 'table', 'feedback', 'layout', 'overlay', 'media', 'interaction', 'selection', 'typography'];
  return selected.filter(t => tags[t]).map(t => `- **${t}**: ${tags[t].join(', ')}`).join('\n');
}

function main() {
  console.log('Generating skill ...');
  const template = readFileSync(base('../static/skill-template.md'), 'utf-8');
  const skill = `<!-- Generated by @allianz/ng-aquila v${version} -->\n` +
    template.replace('{{CATALOG}}', buildCatalogTable()).replace('{{TAGS}}', buildTagSection());

  const outPath = base('../generated/skill.md');
  writeContentsToFile({ path: outPath, content: skill });
  console.log(`Skill written to ${outPath}`);
}

main();
