name: CI

on:
  push:
    branches: [main]
  pull_request:

# Cancel in-progress runs when a new workflow with the same ref is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Generate documentation
        run: npm run library:generate:docs

      - name: Lint check
        run: npm run lint

      - name: Format check
        run: npm run format

      - name: Test ngx-docs-ui
        run: COMPACT_TEST_RESULTS=true npm run test:docs-ui:coverage

      - name: Test ng-aquila
        run: |
          export CHROME_BIN=$(command -v google-chrome || command -v chromium)
          echo "Using browser: $CHROME_BIN"
          COMPACT_TEST_RESULTS=true npm run test:lib:coverage

      - name: Test ng-aquila/schematics
        run: npm run test:schematics

      - name: Build ng-aquila
        run: npm run build:lib

      - name: Build documentation
        run: npm run build:docs -- --progress=false
